### ISSUE TITLE
咱就是说，放了一个邮箱为什么能收到这么多条不同人发的威胁情报

### ISSUE THREAD

**Issue by ChixyCR** [lyy289065406/threat-broadcast#79]
![AE8BA5C9-483C-4B7C-8754-3FE0C4445C0B](https://user-images.githubusercontent.com/25520146/145353254-642845ed-0753-4ccc-aca7-073029a212cc.png)

**Comment by lyy289065406** [comment]
估计都是模仿的，然后把这里邮箱抓了过去，小心被钓鱼，其他邮箱的超链不要点
